# name file
name: ci

# on command describes when the workflow runs
on:
  push:
  pull_request:

# create list of jobs
jobs:
  run-tests:
    # strategy describes what to do when one test fails 
    # false means it will keep excuting all tests
    strategy:
      fail-fast: false
      # set matrix to test on multiple operating system/python types
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    # name job
    name: Test
    # access all the os set in matrix above
    runs-on: ${{ matrix.os }}

    # list steps
    steps:
      # built in github actions way to access the tests
      - name: Checkout code
        uses: actions/checkout@v3

      # set version of python, with multiple in matrix it iterates through them
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # installing pytest
      - name: Install Dependencies
        run: python -m pip install pytest .

      # running pytests
      - name: Run Tests
        run: pytest
